### ISSUE TITLE
Error retrieving node details from Ironic API

### ISSUE THREAD

**Issue by openstack-gopher** [rackerlabs/onmetal-dashboard#2]
Dear colleague,
I have set properly the credentials to access the Ironic API in the software.

However, am getting the following error:

[XX.XX.XXX.XX] error: {
  "msg": "Error retrieving node details from Ironic API",
  "err": {
    "message": "Unable to find tenants",
    "stack": "Error: Unable to find tenants\n    at Request._callback (gitRepos/onmetal-
dashboard/node_modules/pkgcloud/lib/pkgcloud/openstack/context/identity.js:158:41)\n    at Request.self.callback 

(gitRepos/onmetal-dashboard/node_modules/pkgcloud/node_modules/request/index.js:148:22)\n    at Request.emit 

(events.js:110:17)\n    at Request.<anonymous> (gitRepos/onmetal-
dashboard/node_modules/pkgcloud/node_modules/request/index.js:886:14)\n    at Request.emit (events.js:129:20)\n    at 

IncomingMessage.<anonymous> (gitRepos/onmetal-dashboard/node_modules/pkgcloud/node_modules/request/index.js:837:12)\n  

  at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickCallback (node.js:355:11)"
  },
  "class": "datacache",
  "method": "_retrieveNodeDetails"
}
Error on auto refresh
Host in error should be: XX.XX.XXX.XX
{ msg: 'Error retrieving node details from Ironic API',
  err: [Error: Unable to find tenants],
  class: 'datacache',
  method: '_retrieveNodeDetails' }

May I ask for your help in solving the issue, please?
thanks

**Comment by MarkOSullivan94** [comment]
I'm getting the same error
